# Generated by Django 4.0.6 on 2022-08-02 09:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lost', '0004_alter_lostanimal_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalToGoodHands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Кличка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phoneNumber', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lost.animaltype', verbose_name='Тип животного')),
            ],
            options={
                'verbose_name': 'Животное в добрые руки',
                'verbose_name_plural': 'Животные в добрые руки',
                'ordering': ['-published'],
            },
        ),
    ]
