# Generated by Django 4.0.6 on 2022-08-01 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип животного',
                'verbose_name_plural': 'Типы животных',
            },
        ),
        migrations.CreateModel(
            name='LostAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Кличка')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y-%m-d/', verbose_name='Фото')),
                ('place', models.CharField(max_length=200, verbose_name='Где пропал(а)')),
                ('time', models.CharField(blank=True, max_length=200, verbose_name='Когда пропал')),
                ('special_signs', models.CharField(blank=True, max_length=200, verbose_name='Особые приметы')),
                ('description', models.TextField(verbose_name='Подробности')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lost.animaltype', verbose_name='Тип животного')),
            ],
            options={
                'verbose_name': 'Пропавшее животное',
                'verbose_name_plural': 'Пропавшие животные',
                'ordering': ['-published'],
            },
        ),
    ]
