# Generated by Django 4.0.6 on 2022-08-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalanimalmodel',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
    ]
