# Generated by Django 4.0.6 on 2022-08-03 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0002_generalanimalmodel_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalanimalmodel',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон для связи'),
        ),
    ]
