# Generated by Django 4.0.6 on 2022-08-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0003_alter_generalanimalmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalanimalmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
